export const featureOptions = [
  { value: 'distronic_plus', labelKey: 'options.feature.distronic_plus' },
  { value: 'lane_assist', labelKey: 'options.feature.lane_assist' },
  { value: 'active_park_assist', labelKey: 'options.feature.active_park_assist' },
  { value: 'panoramic_roof', labelKey: 'options.feature.panoramic_roof' },
  { value: 'keyless_go', labelKey: 'options.feature.keyless_go' },
  { value: 'xenon_headlights', labelKey: 'options.feature.xenon_headlights' },
  { value: 'heated_mirrors', labelKey: 'options.feature.heated_mirrors' },
  { value: 'power_mirrors', labelKey: 'options.feature.power_mirrors' },
  { value: 'massage_seats', labelKey: 'options.feature.massage_seats' },
  { value: 'heated_cooled_seats', labelKey: 'options.feature.heated_cooled_seats' },
  { value: 'digital_cockpit', labelKey: 'options.feature.digital_cockpit' },
  { value: 'rear_tv', labelKey: 'options.feature.rear_tv' },
  { value: 'alcantara_ceiling', labelKey: 'options.feature.alcantara_ceiling' },
  { value: 'power_trunk', labelKey: 'options.feature.power_trunk' },
  { value: 'ambient_light', labelKey: 'options.feature.ambient_light' },
  { value: 'full_led_headlights', labelKey: 'options.feature.full_led_headlights' },
  { value: 'privacy_glass', labelKey: 'options.feature.privacy_glass' },
  { value: 'rain_sensor', labelKey: 'options.feature.rain_sensor' },
  { value: 'light_sensor', labelKey: 'options.feature.light_sensor' },
  { value: 'steering_controls', labelKey: 'options.feature.steering_controls' },
  { value: 'distance_display', labelKey: 'options.feature.distance_display' },
  { value: 'blind_spot_triangle', labelKey: 'options.feature.blind_spot_triangle' },
  { value: 'navigation', labelKey: 'options.feature.navigation' },
  { value: 'parking_sensors', labelKey: 'options.feature.parking_sensors' },
  { value: 'new_tires', labelKey: 'options.feature.new_tires' },
  { value: 'cruise_control', labelKey: 'options.feature.cruise_control' },
  { value: 'eco_mode', labelKey: 'options.feature.eco_mode' },
] as const;

export const featureGroupTitleKey = 'options.group.features';

export const selectOptionGroups = [
  {
    key: 'climate',
    titleKey: 'options.group.climate',
    options: [
      { value: '2_zone', labelKey: 'options.climate.2_zone' },
      { value: '4_zone', labelKey: 'options.climate.4_zone' },
    ],
  },
  {
    key: 'interior',
    titleKey: 'options.group.interior',
    options: [
      { value: 'leather', labelKey: 'options.interior.leather' },
      { value: 'fabric', labelKey: 'options.interior.fabric' },
      { value: 'alcantara', labelKey: 'options.interior.alcantara' },
    ],
  },
  {
    key: 'drivetrain',
    titleKey: 'options.group.drivetrain',
    options: [
      { value: 'awd_4matic', labelKey: 'options.drivetrain.awd_4matic' },
      { value: 'rwd', labelKey: 'options.drivetrain.rwd' },
      { value: 'fwd', labelKey: 'options.drivetrain.fwd' },
    ],
  },
  {
    key: 'registration',
    titleKey: 'options.group.registration',
    options: [
      { value: 'with_documents_plate', labelKey: 'options.registration.with_documents_plate' },
      { value: 'with_plate', labelKey: 'options.registration.with_plate' },
      { value: 'with_customs', labelKey: 'options.registration.with_customs' },
      { value: 'without_customs', labelKey: 'options.registration.without_customs' },
    ],
  },
] as const;

export const optionLabelLookup = new Map<string, string>([
  ...featureOptions.map((item) => [item.value, item.labelKey] as const),
  ...selectOptionGroups.flatMap((group) => group.options.map((opt) => [opt.value, opt.labelKey] as const)),
  ['Distronic Plus', 'options.feature.distronic_plus'],
  ['Ruajtja e Korsise', 'options.feature.lane_assist'],
  ['Vetparkim', 'options.feature.active_park_assist'],
  ['Tavan Panoramik', 'options.feature.panoramic_roof'],
  ['Ndezje me Buton', 'options.feature.keyless_go'],
  ['Fenere Xenon', 'options.feature.xenon_headlights'],
  ['Pasqyra me Ngrohje', 'options.feature.heated_mirrors'],
  ['Pasqyra Elektrike', 'options.feature.power_mirrors'],
  ['Sedilje me Masazh', 'options.feature.massage_seats'],
  ['Ngrohje & Ftohje Sediljesh', 'options.feature.heated_cooled_seats'],
  ['Kroskot Dixhital', 'options.feature.digital_cockpit'],
  ['TV Mbrapa', 'options.feature.rear_tv'],
  ['Tavan Kamosh', 'options.feature.alcantara_ceiling'],
  ['Bagazh me Buton', 'options.feature.power_trunk'],
  ['Ndricim Ambienti', 'options.feature.ambient_light'],
  ['Fenere Full LED', 'options.feature.full_led_headlights'],
  ['Xhama te Zi', 'options.feature.privacy_glass'],
  ['Sensor Shiu', 'options.feature.rain_sensor'],
  ['Sensor Dritash', 'options.feature.light_sensor'],
  ['Komanda ne Timon', 'options.feature.steering_controls'],
  ['Distance Display', 'options.feature.distance_display'],
  ['Trekendesh ne pasqyre', 'options.feature.blind_spot_triangle'],
  ['Navigator', 'options.feature.navigation'],
  ['Sensor Parkimi', 'options.feature.parking_sensors'],
  ['Goma te Reja', 'options.feature.new_tires'],
  ['Cruise Control', 'options.feature.cruise_control'],
  ['Eco Mode', 'options.feature.eco_mode'],
  ['2 zona', 'options.climate.2_zone'],
  ['4 zona', 'options.climate.4_zone'],
  ['Sallon Lekure', 'options.interior.leather'],
  ['Sallon Robe', 'options.interior.fabric'],
  ['Sallon Kamosh', 'options.interior.alcantara'],
  ['Traksioni 4x4 (4 matic)', 'options.drivetrain.awd_4matic'],
  ['Diferencial mbrapa (RWD)', 'options.drivetrain.rwd'],
  ['Diferencial para', 'options.drivetrain.fwd'],
  ['Me letra/Targa', 'options.registration.with_documents_plate'],
  ['Me targa', 'options.registration.with_plate'],
  ['Me dogane', 'options.registration.with_customs'],
  ['Pa dogane', 'options.registration.without_customs'],
]);

export const optionGroupTitleLookup = new Map<string, string>([
  [featureGroupTitleKey, featureGroupTitleKey],
  ...selectOptionGroups.map((group) => [group.titleKey, group.titleKey] as const),
  ['Opsionet', featureGroupTitleKey],
  ['Klima', 'options.group.climate'],
  ['Sallon', 'options.group.interior'],
  ['Traksioni', 'options.group.drivetrain'],
  ['Leje/Targa', 'options.group.registration'],
]);
